[project]
name = "hackathon2026flower"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flwr==1.37.0",
]

[project.scripts]
hackathon2026flower = "hackathon2026flower:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
