"""Loads the team's on-farm irrigation dataset.

The data is **synthetic** -- generated by `data/generate_data.py` against the
rules in `data/DATA_SPEC.md`, not measured on real farms. Every accuracy figure
in this project is therefore a statement about how well the model recovers a
generator's rules, not about how well it would advise a real farmer. The
agronomic structure (crop coefficients, growth stages, soil water capacity) is
plausible, but real sensor noise, failure modes and regional drift are absent,
so error on real data would very likely be larger.

Rows come from `data/partitions.csv` (one row = one field on one morning),
split on `farm_id` into Flower partitions, joined to `data/regional_weather.csv`
by date. Column names, label mapping and allowed
values follow `data/DATA_SPEC.md` and must not be renamed.

Two things about this data shape the whole project:

1. The label is three-class and badly imbalanced -- roughly 76% Low, 21% Medium,
   2% High. Accuracy is therefore a useless metric: always predicting Low scores
   76%. Macro-F1 and High-class recall are what matter.
2. The farms are *specialised*: farmer_1 grows only potato on sand, farmer_2 only
   maize on loam. Neither has ever observed the other's crop, so a solo model is
   not merely weaker off its own ground -- it has no signal there at all. This is
   the sharpest version of the argument for federating.
3. Roughly 2% of soil-moisture cells are empty (sensor dropout) and some sensors
   stick on the last reading for days. Missing values are imputed to the regional
   mean, which in standardized space is exactly zero -- see `encode`.
"""

from __future__ import annotations

import csv
import json
import os
from pathlib import Path

import numpy as np

def _resolve_data_dir() -> Path:
    """Find the dataset, whether running from the repo or from an installed FAB.

    A FAB is unpacked into ~/.flwr/apps/<app>/, far from the repo, so the CSVs
    have to travel inside it -- `scripts/sync-data.sh` copies them into the
    package and `fab-include` ships them. The repo-root path is kept as a
    fallback so `python -c` against a checkout still works.
    """
    override = os.environ.get("GROWFLWR_DATA_DIR")
    if override:
        return Path(override).expanduser()

    bundled = Path(__file__).resolve().parent / "dataset"
    if bundled.exists():
        return bundled

    return Path(__file__).resolve().parents[2] / "data"


DATA_DIR = _resolve_data_dir()

NUM_CLASSES = 3
CLASS_NAMES = {0: "Low", 1: "Medium", 2: "High"}

# Numeric columns, then regional weather joined by date.
NUMERIC = [
    "soil_moisture_pct_nfk",
    "days_since_last_irrigation",
    "previous_irrigation_mm",
    "onfarm_rain_gauge_mm",
    "days_after_planting",
    "et0_mm",
    "rain_mm",
]

# Fixed vocabularies from DATA_SPEC.md. Every client must encode identically or
# the averaged weights are meaningless, so these are hard-coded rather than
# inferred from whatever rows a given farm happens to hold.
CATEGORICAL = {
    "growth_stage": ["initial", "development", "sensitive", "late"],
    "crop_type": ["potato", "maize", "sugar_beet"],
    "soil_type": ["sand", "loamy_sand", "loam"],
    "crop_variety_maturity": ["early", "medium", "late"],
    "irrigation_type": ["hose_reel", "pivot", "drip"],
}

# Regional normalization constants, computed once from the pooled baseline and
# published by the authority. Deriving these per-farm would make each client's
# feature space different and quietly break averaging.
FEATURE_STATS = {
    "soil_moisture_pct_nfk": (57.88, 13.84),
    "days_since_last_irrigation": (9.54, 11.65),
    "previous_irrigation_mm": (17.78, 10.87),
    "onfarm_rain_gauge_mm": (0.84, 2.65),
    "days_after_planting": (81.95, 47.22),
    "et0_mm": (4.22, 1.35),
    "rain_mm": (0.82, 3.02),
}

_ONE_HOT_NAMES = [
    f"{col}={value}" for col, values in CATEGORICAL.items() for value in values
]

# Interaction terms: soil moisture multiplied by each crop and each growth
# stage indicator.
#
# DATA_SPEC defines the label as "moisture below a threshold that depends on
# crop and growth stage". A purely additive model has no way to express a
# crop-specific threshold -- it gets one slope for moisture and must apply it
# everywhere. These terms give it one slope per crop and per stage, which is
# what the rule actually is. Measured: macro-F1 0.704 -> 0.732.
INTERACTIONS = (
    [f"soil_moisture x crop_type={v}" for v in CATEGORICAL["crop_type"]]
    + [f"soil_moisture x growth_stage={v}" for v in CATEGORICAL["growth_stage"]]
)

FEATURE_NAMES = NUMERIC + _ONE_HOT_NAMES + INTERACTIONS
N_FEATURES = len(FEATURE_NAMES)
_N_BASE = len(NUMERIC) + len(_ONE_HOT_NAMES)

# Test split: train on the 2025 season, test on 2026.
#
# The dataset now spans two seasons, so the honest evaluation is "predict a year
# you have not seen" -- new weather, new drought timing. That is what a farmer
# actually faces. An earlier field-level holdout was used when only one season
# existed; this supersedes it.
TEST_YEAR = "2026"

# Partitions are farm_id values inside one file.
FARM_IDS = ["farmer_1", "farmer_2"]
NUM_FARMS = len(FARM_IDS)


def _rows(name: str) -> list[dict[str, str]]:
    """Read one dataset, preferring the bundled JSONL over a repo-root CSV.

    A FAB carries no .csv (flwr/common/constant.py:71), so `sync-data.sh`
    converts them; the CSV branch only fires when running against a checkout.
    """
    jsonl = DATA_DIR / f"{name}.jsonl"
    if jsonl.exists():
        with jsonl.open() as fh:
            return [json.loads(line) for line in fh if line.strip()]

    csv_path = DATA_DIR / f"{name}.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"No {name}.jsonl or {name}.csv in {DATA_DIR}. "
            f"Run scripts/sync-data.sh."
        )
    with csv_path.open() as fh:
        return list(csv.DictReader(fh))


def _weather() -> dict[str, dict[str, float]]:
    return {
        row["date"]: {"et0_mm": float(row["et0_mm"]), "rain_mm": float(row["rain_mm"])}
        for row in _rows("regional_weather")
    }


def encode(row: dict[str, str], weather_day: dict[str, float]) -> np.ndarray:
    """Turn one data row plus that day's regional weather into a feature vector."""
    vec = np.zeros(N_FEATURES, dtype=np.float64)

    for i, name in enumerate(NUMERIC):
        mean, std = FEATURE_STATS[name]
        if name in weather_day:
            vec[i] = (float(weather_day[name]) - mean) / std
            continue
        raw = row.get(name, "")
        if raw in ("", None):
            # Sensor dropout: ~2% of soil-moisture cells are empty. Impute the
            # regional mean, which is 0 in standardized space -- the feature
            # simply stops contributing rather than the row being discarded.
            vec[i] = 0.0
        else:
            vec[i] = (float(raw) - mean) / std

    offset = len(NUMERIC)
    blocks: dict[str, tuple[int, int]] = {}
    for col, values in CATEGORICAL.items():
        blocks[col] = (offset, len(values))
        value = row[col]
        if value in values:
            vec[offset + values.index(value)] = 1.0
        # An unseen category leaves the block all-zero rather than raising: the
        # spec fixes the vocabulary, but a future data drop should not crash a
        # client mid-round.
        offset += len(values)

    moisture = vec[NUMERIC.index("soil_moisture_pct_nfk")]
    at = _N_BASE
    for col in ("crop_type", "growth_stage"):
        start, size = blocks[col]
        vec[at:at + size] = moisture * vec[start:start + size]
        at += size

    return vec


def _load_partition(farm_id: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    weather = _weather()
    xs, ys, years = [], [], []

    for row in _rows("partitions"):
        if row["farm_id"] != farm_id:
            continue
        day = weather.get(row["date"])
        if day is None:
            continue  # no weather for that date; skip rather than impute
        xs.append(encode(row, day))
        ys.append(int(row["irrigation_need"]))
        years.append(row["date"][:4])

    return np.array(xs), np.array(ys, dtype=np.int64), np.array(years)


def farm_data(partition_id: int) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return (x_train, y_train, x_test, y_test) for one farm, split by season."""
    x, y, years = _load_partition(FARM_IDS[partition_id])
    train = years != TEST_YEAR
    return x[train], y[train], x[~train], y[~train]


def region_data() -> tuple[np.ndarray, np.ndarray]:
    """Pooled held-out set across every farm — what the authority evaluates on."""
    xs, ys = [], []
    for fid in range(NUM_FARMS):
        _, _, x_test, y_test = farm_data(fid)
        xs.append(x_test)
        ys.append(y_test)
    return np.vstack(xs), np.concatenate(ys)


def farm_name(partition_id: int) -> str:
    return FARM_IDS[partition_id]


# Columns the spec marks agent_only: not federated training features, but the
# agent needs them to turn a class into an instruction in litres.
AGENT_ONLY = ["water_source", "field_area_ha", "irrigation_type", "crop_type"]


def latest_rows(partition_id: int) -> list[dict[str, str]]:
    """The most recent morning observation for each of this farm's fields.

    Stands in for the farm gateway publishing its current state. The AgentApp
    has no route to farm systems, so this travels with the app.
    """
    rows = [r for r in _rows("partitions")
            if r["farm_id"] == FARM_IDS[partition_id]]
    newest: dict[str, dict[str, str]] = {}
    for row in rows:
        field = row["field_id"]
        if field not in newest or row["date"] > newest[field]["date"]:
            newest[field] = row
    return [newest[key] for key in sorted(newest)]
