"""Loads the team's on-farm irrigation dataset.

The data is **synthetic** -- generated by `data/generate_data.py` against the
rules in `data/DATA_SPEC.md`, not measured on real farms. Every accuracy figure
in this project is therefore a statement about how well the model recovers a
generator's rules, not about how well it would advise a real farmer. The
agronomic structure (crop coefficients, growth stages, soil water capacity) is
plausible, but real sensor noise, failure modes and regional drift are absent,
so error on real data would very likely be larger.

Rows come from `data/farm_*.csv` (one row = one field on one morning) joined to
`data/regional_weather.csv` by date. Column names, label mapping and allowed
values follow `data/DATA_SPEC.md` and must not be renamed.

Two things about this data shape the whole project:

1. The label is three-class and badly imbalanced -- roughly 76% Low, 21% Medium,
   2% High. Accuracy is therefore a useless metric: always predicting Low scores
   76%. Macro-F1 and High-class recall are what matter.
2. High is rare *per farm*: 10-18 examples across an entire season. That is too
   few to learn from alone and is exactly what federating fixes -- pooled, there
   are 54. This is the strongest argument the project has.
"""

from __future__ import annotations

import csv
import json
import os
from pathlib import Path

import numpy as np

def _resolve_data_dir() -> Path:
    """Find the dataset, whether running from the repo or from an installed FAB.

    A FAB is unpacked into ~/.flwr/apps/<app>/, far from the repo, so the CSVs
    have to travel inside it -- `scripts/sync-data.sh` copies them into the
    package and `fab-include` ships them. The repo-root path is kept as a
    fallback so `python -c` against a checkout still works.
    """
    override = os.environ.get("GROWFLWR_DATA_DIR")
    if override:
        return Path(override).expanduser()

    bundled = Path(__file__).resolve().parent / "dataset"
    if bundled.exists():
        return bundled

    return Path(__file__).resolve().parents[2] / "data"


DATA_DIR = _resolve_data_dir()

NUM_CLASSES = 3
CLASS_NAMES = {0: "Low", 1: "Medium", 2: "High"}

# Numeric columns, then regional weather joined by date.
NUMERIC = [
    "soil_moisture_pct_nfk",
    "days_since_last_irrigation",
    "previous_irrigation_mm",
    "onfarm_rain_gauge_mm",
    "days_after_planting",
    "et0_mm",
    "rain_mm",
]

# Fixed vocabularies from DATA_SPEC.md. Every client must encode identically or
# the averaged weights are meaningless, so these are hard-coded rather than
# inferred from whatever rows a given farm happens to hold.
CATEGORICAL = {
    "growth_stage": ["initial", "development", "sensitive", "late"],
    "crop_type": ["potato", "maize", "sugar_beet"],
    "soil_type": ["sand", "loamy_sand", "loam"],
    "crop_variety_maturity": ["early", "medium", "late"],
    "irrigation_type": ["hose_reel", "pivot", "drip"],
}

# Regional normalization constants, computed once from the pooled baseline and
# published by the authority. Deriving these per-farm would make each client's
# feature space different and quietly break averaging.
FEATURE_STATS = {
    "soil_moisture_pct_nfk": (60.75, 14.37),
    "days_since_last_irrigation": (11.77, 11.21),
    "previous_irrigation_mm": (21.54, 14.69),
    "onfarm_rain_gauge_mm": (1.15, 3.51),
    "days_after_planting": (83.87, 47.86),
    "et0_mm": (3.78, 0.86),
    "rain_mm": (1.08, 3.66),
}

_ONE_HOT_NAMES = [
    f"{col}={value}" for col, values in CATEGORICAL.items() for value in values
]

# Interaction terms: soil moisture multiplied by each crop and each growth
# stage indicator.
#
# DATA_SPEC defines the label as "moisture below a threshold that depends on
# crop and growth stage". A purely additive model has no way to express a
# crop-specific threshold -- it gets one slope for moisture and must apply it
# everywhere. These terms give it one slope per crop and per stage, which is
# what the rule actually is. Measured: macro-F1 0.704 -> 0.732.
INTERACTIONS = (
    [f"soil_moisture x crop_type={v}" for v in CATEGORICAL["crop_type"]]
    + [f"soil_moisture x growth_stage={v}" for v in CATEGORICAL["growth_stage"]]
)

FEATURE_NAMES = NUMERIC + _ONE_HOT_NAMES + INTERACTIONS
N_FEATURES = len(FEATURE_NAMES)
_N_BASE = len(NUMERIC) + len(_ONE_HOT_NAMES)

# Test split: hold out each farm's last field entirely.
#
# Splitting by date was tried first and left only 2 High rows in the whole
# regional test set -- High clusters in midsummer and the season ends in
# September -- which makes the one metric that matters unmeasurable. Splitting
# by field keeps the label distribution while still avoiding leakage between
# consecutive days of the same field. "Last field" is a fixed rule, not a
# choice made after looking at which split scored best.

NUM_FARMS = 4


def _rows(name: str) -> list[dict[str, str]]:
    """Read one dataset, preferring the bundled JSONL over a repo-root CSV.

    A FAB carries no .csv (flwr/common/constant.py:71), so `sync-data.sh`
    converts them; the CSV branch only fires when running against a checkout.
    """
    jsonl = DATA_DIR / f"{name}.jsonl"
    if jsonl.exists():
        with jsonl.open() as fh:
            return [json.loads(line) for line in fh if line.strip()]

    csv_path = DATA_DIR / f"{name}.csv"
    if not csv_path.exists():
        raise FileNotFoundError(
            f"No {name}.jsonl or {name}.csv in {DATA_DIR}. "
            f"Run scripts/sync-data.sh."
        )
    with csv_path.open() as fh:
        return list(csv.DictReader(fh))


def _weather() -> dict[str, dict[str, float]]:
    return {
        row["date"]: {"et0_mm": float(row["et0_mm"]), "rain_mm": float(row["rain_mm"])}
        for row in _rows("regional_weather")
    }


def encode(row: dict[str, str], weather_day: dict[str, float]) -> np.ndarray:
    """Turn one data row plus that day's regional weather into a feature vector."""
    vec = np.zeros(N_FEATURES, dtype=np.float64)

    for i, name in enumerate(NUMERIC):
        raw = weather_day[name] if name in weather_day else float(row[name])
        mean, std = FEATURE_STATS[name]
        vec[i] = (float(raw) - mean) / std

    offset = len(NUMERIC)
    blocks: dict[str, tuple[int, int]] = {}
    for col, values in CATEGORICAL.items():
        blocks[col] = (offset, len(values))
        value = row[col]
        if value in values:
            vec[offset + values.index(value)] = 1.0
        # An unseen category leaves the block all-zero rather than raising: the
        # spec fixes the vocabulary, but a future data drop should not crash a
        # client mid-round.
        offset += len(values)

    moisture = vec[NUMERIC.index("soil_moisture_pct_nfk")]
    at = _N_BASE
    for col in ("crop_type", "growth_stage"):
        start, size = blocks[col]
        vec[at:at + size] = moisture * vec[start:start + size]
        at += size

    return vec


def _load_farm(name: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    weather = _weather()
    xs, ys, fields = [], [], []

    for row in _rows(name):
        day = weather.get(row["date"])
        if day is None:
            continue  # no weather for that date; skip rather than impute
        xs.append(encode(row, day))
        ys.append(int(row["irrigation_need"]))
        fields.append(row["field_id"])

    return np.array(xs), np.array(ys, dtype=np.int64), np.array(fields)


def farm_data(partition_id: int) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return (x_train, y_train, x_test, y_test) for one farm, held out by field."""
    x, y, fields = _load_farm(f"farm_{partition_id + 1}")
    held_out = sorted(set(fields))[-1]
    train = fields != held_out
    return x[train], y[train], x[~train], y[~train]


def region_data() -> tuple[np.ndarray, np.ndarray]:
    """Pooled held-out set across every farm — what the authority evaluates on."""
    xs, ys = [], []
    for fid in range(NUM_FARMS):
        _, _, x_test, y_test = farm_data(fid)
        xs.append(x_test)
        ys.append(y_test)
    return np.vstack(xs), np.concatenate(ys)


def farm_name(partition_id: int) -> str:
    return f"farm_{partition_id + 1}"


# Columns the spec marks agent_only: not federated training features, but the
# agent needs them to turn a class into an instruction in litres.
AGENT_ONLY = ["water_source", "field_area_ha", "irrigation_type", "crop_type"]


def latest_rows(partition_id: int) -> list[dict[str, str]]:
    """The most recent morning observation for each of this farm's fields.

    Stands in for the farm gateway publishing its current state. The AgentApp
    has no route to farm systems, so this travels with the app.
    """
    rows = _rows(f"farm_{partition_id + 1}")
    newest: dict[str, dict[str, str]] = {}
    for row in rows:
        field = row["field_id"]
        if field not in newest or row["date"] > newest[field]["date"]:
            newest[field] = row
    return [newest[key] for key in sorted(newest)]
